name: Deployment

on: push

jobs:
  gem:
    name: Build and publish Gem
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Publish to Rubygems
      uses: sawshep/publish-rubygems-action@v1.1.0
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_COMMAND: "gem build *.gemspec && gem push *.gem"

  aur:
    name: Publish AUR package
    needs:
      - gem

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1.101.0
        with:
          ruby-version: 3.0

      - name: Generate PKGBUILD
        run: ./ci/generate-pkgbuild.rb

      - name: Publish can to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: can
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.COMMIT_USERNAME }}
          commit_email: ${{ secrets.COMMIT_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
